(function(){
'use strict';const $=id=>document.getElementById(id);let ticket=null,pending=null,saving=false,generation=0;
async function api(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);try{const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:controller.signal,cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'接続できませんでした。');return data;}catch(e){throw new Error(e.name==='AbortError'?'接続に時間がかかっています。再試行してください。':e.message==='Failed to fetch'?'保存先に接続できません。再試行してください。':e.message);}finally{clearTimeout(timer);}}
function status(text){$('rank-message').textContent=text;}
async function refresh(){const button=$('rank-refresh');button.disabled=true;try{const data=await api('/api/leaderboard');$('rank-rows').replaceChildren();if(!data.entries.length){status('まだ記録がありません。最初のスコアを残しましょう。');}else{status(data.players+'人が参加・1人につき最高得点を表示');for(const e of data.entries){const tr=document.createElement('tr');if(e.rank<=3)tr.className='rank-top rank-'+e.rank;for(const val of [String(e.rank).padStart(2,'0'),e.name,e.score.toLocaleString(),e.combo+'回']){const td=document.createElement('td');td.textContent=val;tr.append(td);}$('rank-rows').append(tr);}}}catch{status('ランキングに接続できません。「更新」で再試行できます。');}finally{button.disabled=false;}}
rootInit();function rootInit(){window.PRIME_RANKING={
 async begin(standard){generation++;const current=generation;ticket=null;pending=null;$('score-entry').hidden=true;if(!standard){status('練習モード：設定を初期値に戻すとランキングに参加できます。');return;}try{const t=await api('/api/game/start',{ruleset:PRIME_DEFAULTS.RULESET});if(current===generation){ticket=t;status('ランキング対象のプレイです。');}}catch{status('今回は保存先につながらないため練習プレイになります。');}},
 finish(result,events,standard){if(!standard||!ticket){$('save-feedback').textContent=standard?'今回はオンライン記録を開始できなかったため、登録できません。':'設定を変更したプレイはランキング対象外です。';$('score-entry').hidden=false;$('score-form').hidden=true;return;}pending={...ticket,events};$('score-entry').hidden=false;$('score-form').hidden=false;$('save-score').disabled=false;$('save-feedback').textContent='このプレイの '+result.score.toLocaleString()+' 点を登録できます。';try{$('player-name').value=localStorage.getItem('prime-player-name')||'';}catch{}},
 refresh
 };$('rank-refresh').onclick=refresh;$('score-form').onsubmit=async e=>{e.preventDefault();if(!pending||saving)return;saving=true;$('save-score').disabled=true;$('save-feedback').textContent='スコアを確認して保存しています…';try{const data=await api('/api/scores',{...pending,name:$('player-name').value});try{localStorage.setItem('prime-player-name',data.name);}catch{}$('save-feedback').textContent=(data.personalBest?'自己ベスト！ ':'登録しました。 ')+data.rank+'位 / 最高 '+data.best.toLocaleString()+'点';pending=null;await refresh();}catch(err){$('save-feedback').textContent=err.message;$('save-score').disabled=false;}finally{saving=false;}};refresh();document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});}
})();
